/**
 * Centralised error codes for the Vallle app.
 * Attach to Error objects via `err.code = ERROR_CODES.XXX`.
 * Keep alphabetical within each section.
 */
export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

  // Email
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

  // Rate limiting
  RATE_LIMITED: "RATE_LIMITED",

  // Orders
  ORDER_ALREADY_INVOICED: "ORDER_ALREADY_INVOICED",
  ORDER_ALREADY_PAID: "ORDER_ALREADY_PAID",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_NOT_INVOICED: "ORDER_NOT_INVOICED",

  // Password Reset
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
  PASSWORD_RESET_INVALID_TOKEN: "PASSWORD_RESET_INVALID_TOKEN",

  // Database
  DB_READ_FAILED: "DB_READ_FAILED",
  DB_WRITE_FAILED: "DB_WRITE_FAILED",

  // Subscriptions
  SUBSCRIPTION_PERIOD_ALREADY_PAID: "SUBSCRIPTION_PERIOD_ALREADY_PAID",
  SUBSCRIPTION_PERIOD_NOT_FOUND: "SUBSCRIPTION_PERIOD_NOT_FOUND",

  // Stores
  STORE_NOT_FOUND: "STORE_NOT_FOUND",

  // Vallles
  VALLLE_ALREADY_USED: "VALLLE_ALREADY_USED",
  VALLLE_EXPIRED: "VALLLE_EXPIRED",
  VALLLE_INSUFFICIENT_BALANCE: "VALLLE_INSUFFICIENT_BALANCE",
  VALLLE_NOT_FOUND: "VALLLE_NOT_FOUND",

  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",
};
