/**
 * Centralised error codes for the Vallle app.
 * Attach to Error objects via `err.code = ERROR_CODES.XXX`.
 * Keep alphabetical within each section.
 */
export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // Email
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

  // Password Reset
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  PASSWORD_RESET_INVALID_TOKEN: 'PASSWORD_RESET_INVALID_TOKEN',

  // Database
  DB_READ_FAILED: 'DB_READ_FAILED',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',

  // Commissions
  COMMISSION_NOT_FOUND: 'COMMISSION_NOT_FOUND',

  // Stores
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',

  // Vouchers
  VOUCHER_ALREADY_USED: 'VOUCHER_ALREADY_USED',
  VOUCHER_EXPIRED: 'VOUCHER_EXPIRED',
  VOUCHER_INSUFFICIENT_BALANCE: 'VOUCHER_INSUFFICIENT_BALANCE',
  VOUCHER_NOT_FOUND: 'VOUCHER_NOT_FOUND',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
}
